from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path
from unittest import TestCase


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from agent_watcher.models import TargetRepo
from agent_watcher.reporting import render_report
from agent_watcher.watcher import scan_target


class FakeGitHubClient:
    def __init__(self, items, comments=None, prs=None, reviews=None):
        self.items = items
        self.comments = comments or {}
        self.prs = prs or {}
        self.reviews = reviews or {}

    def list_recent_issues_and_prs(self, repo, *, since, max_items):
        return self.items[:max_items]

    def list_issue_comments(self, repo, number, *, max_comments):
        return self.comments.get(number, [])[:max_comments]

    def list_pr_reviews(self, repo, number, *, max_reviews):
        return self.reviews.get(number, [])[:max_reviews]

    def get_pr(self, repo, number):
        return self.prs.get(number, {"merged_at": None})


TARGET = TargetRepo(
    repo="example/repo",
    display_name="Example",
    short_name="repo",
    lookback_days=7,
    max_items=10,
    max_comments_per_item=10,
    report_timezone="America/Los_Angeles",
    issue_mode="dated",
    issue_title_template="{short_name} report for {report_date}",
    cadence="weekly",
    preferred_weekday_utc=0,
    preferred_hour_utc=13,
    extra_prompt="",
    agent_login_substrings=("dragon-ai-agent", "claude", "codex"),
    agent_text_patterns=("@dragon-ai-agent", "claude code"),
)


class WatcherTests(TestCase):
    def test_collects_event_timeline_and_counts_for_agent_pr(self):
        client = FakeGitHubClient(
            items=[
                {
                    "number": 101,
                    "title": "Add missing relationship",
                    "html_url": "https://github.com/example/repo/pull/101",
                    "state": "closed",
                    "created_at": "2026-03-29T10:00:00Z",
                    "updated_at": "2026-03-29T11:00:00Z",
                    "body": "Generated by @dragon-ai-agent",
                    "user": {"login": "dragon-ai-agent"},
                    "pull_request": {"url": "https://api.github.com/repos/example/repo/pulls/101"},
                }
            ],
            prs={101: {"merged_at": "2026-03-29T11:00:00Z"}},
        )

        report = scan_target(client, TARGET, generated_at=_dt("2026-03-30T00:00:00Z"))

        self.assertEqual(report.metrics["merged_prs"], 1)
        self.assertEqual(report.metrics["agent_items"], 1)
        self.assertEqual(report.metrics["agent_summons"], 1)
        self.assertEqual(report.issue_title, "repo report for 2026-03-29")
        self.assertEqual(len(report.tracked_items[0].events), 1)

    def test_marks_human_follow_up_and_renders_context_timeline(self):
        client = FakeGitHubClient(
            items=[
                {
                    "number": 202,
                    "title": "Need curation help",
                    "html_url": "https://github.com/example/repo/issues/202",
                    "state": "open",
                    "created_at": "2026-03-29T08:00:00Z",
                    "updated_at": "2026-03-29T12:00:00Z",
                    "body": "@dragon-ai-agent please help",
                    "user": {"login": "curator-1"},
                },
                {
                    "number": 203,
                    "title": "Another follow-up",
                    "html_url": "https://github.com/example/repo/issues/203",
                    "state": "open",
                    "created_at": "2026-03-29T08:00:00Z",
                    "updated_at": "2026-03-29T13:00:00Z",
                    "body": "@dragon-ai-agent please help",
                    "user": {"login": "curator-2"},
                },
            ],
            comments={
                202: [
                    _comment("dragon-ai-agent", "2026-03-29T09:00:00Z", "I opened a PR."),
                    _comment("curator-1", "2026-03-29T12:00:00Z", "This still needs work."),
                ],
                203: [
                    _comment("dragon-ai-agent", "2026-03-29T09:00:00Z", "Investigating."),
                    _comment("curator-2", "2026-03-29T13:00:00Z", "Can you address the parent term too?"),
                ],
            },
        )

        report = scan_target(client, TARGET, generated_at=_dt("2026-03-30T00:00:00Z"))
        rendered = render_report(report)

        self.assertEqual(report.metrics["stalled_items"], 2)
        self.assertEqual(report.metrics["agent_items"], 2)
        self.assertIn("#### Event Timeline", rendered)
        self.assertIn("human follow-up after latest agent action", rendered)
        self.assertIn("Agent summons / references", rendered)
        self.assertIn("Suggested issue title", rendered)

    def test_surfaces_recent_open_non_agent_issues_as_potential_opportunities(self):
        client = FakeGitHubClient(
            items=[
                {
                    "number": 301,
                    "title": "Add missing xref to mature cell term",
                    "html_url": "https://github.com/example/repo/issues/301",
                    "state": "open",
                    "created_at": "2026-03-29T08:00:00Z",
                    "updated_at": "2026-03-29T12:00:00Z",
                    "body": "This should be a narrow ontology edit with a straightforward PR.",
                    "user": {"login": "curator-1"},
                },
                {
                    "number": 302,
                    "title": "Discussion: longer term roadmap",
                    "html_url": "https://github.com/example/repo/issues/302",
                    "state": "closed",
                    "created_at": "2026-03-29T08:00:00Z",
                    "updated_at": "2026-03-29T12:00:00Z",
                    "body": "Not open, so not an opportunity.",
                    "user": {"login": "curator-2"},
                },
            ],
            comments={
                301: [
                    _comment("curator-1", "2026-03-29T12:00:00Z", "Likely a quick follow-up if someone picks it up."),
                ],
            },
        )

        report = scan_target(client, TARGET, generated_at=_dt("2026-03-30T00:00:00Z"))
        rendered = render_report(report)

        self.assertEqual(report.metrics["agent_items"], 0)
        self.assertEqual(report.metrics["potential_opportunities"], 1)
        self.assertEqual(len(report.opportunity_items), 1)
        self.assertIn("## Potential Missed Opportunities", rendered)
        self.assertIn("Why surfaced: recent open issue with no detected agent involvement", rendered)
        self.assertIn("Add missing xref to mature cell term", rendered)


def _comment(login: str, created_at: str, body: str) -> dict:
    return {
        "user": {"login": login},
        "created_at": created_at,
        "html_url": "https://github.com/example/repo/issues/1#issuecomment-1",
        "body": body,
    }


def _dt(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)
